server:
  port: 8083
spring:
  application.name: backend-gateway-client
  cloud:
    gateway:
      routes:
        - id: ponto-eletronico
          uri: http://localhost:8080
          predicates:
            Path=/v**/ponto-eletronico/**
        - id: relatorios
          uri: http://localhost:8081
          predicates:
            Path=/v**/relatorios/**
        - id: funcionarios
          uri: http://localhost:8082
          predicates:
            Path=/v**/funcionarios/**
spring.security.oauth2:
  resourceserver:
    jwt:
      jwk-set-uri: http://localhost:9080/realms/test/protocol/openid-connect/certs
  client:
    provider:
      keycloak:
        issuer-uri: http://localhost:9080/realms/test
    registration:
      spring-with-test-scope:
        provider: keycloak
        client-id: funcionario
        client-secret: dZuVrdf1zt4tlyGQTIkmyP9eWbXwBOav
        authorization-grant-type: authorization_code
        scope: openid