server:
  port: 8080

logging:
  level:
    root: ${LOGGING_LEVEL_ROOT}

spring:
  profiles:
    active: dev
  application.name: backend-gateway-client
  cloud:
    gateway:
      routes:
        - id: ponto-eletronico
          uri: ${API_PONTO_ELETRONICO}
          predicates:
            Path=/v**/ponto-eletronico/**
        - id: relatorios
          uri: ${API_RELATORIO}
          predicates:
            Path=/v**/relatorios/**
        - id: funcionarios
          uri: ${API_FUNCIONARIOS}
          predicates:
            Path=/v**/funcionarios/**
spring.security.oauth2:
  resourceserver:
    jwt:
      jwk-set-uri: ${KEYCLOAK_URL}/realms/test/protocol/openid-connect/certs
  client:
    provider:
      keycloak:
        issuer-uri: ${KEYCLOAK_URL}/realms/test
    registration:
      spring-with-test-scope:
        provider: keycloak
        client-id: ${KEYCLOAK_CLIENT_ID}
        client-secret: ${KEYCLOAK_CLIENT_SECRET}
        authorization-grant-type: authorization_code
        scope: openid